Repository Abayev-Bayazit1/Project_5, pull requests merged in 2025-02, with the labels that each got.

#76 Room Category Repo
  src/Main.java
  src/models/Room.java
  src/repository/RoomCategoryRepository.java
  src/repository/interfaces/IRoomCategoryRepository.java
Labels: Classes and Packages, backend

#77 updated Room Repo
  src/repository/RoomRepository.java
Labels: backend

#85 creating lambda in MyApplication for viewCategories
  README.md
  src/MyApplication.java
Labels: bug

#86 fix some bugs
  src/MyApplication.java
  src/controllers/UserController.java
  src/repository/BookingRepository.java
  src/services/BookingService.java
Labels: bug

#88 added method Delete Category
  src/MyApplication.java
  src/controllers/RoomCategoryController.java
  src/repository/RoomCategoryRepository.java
  src/repository/RoomRepository.java
  src/repository/interfaces/IRoomCategoryRepository.java
  src/services/RoomCategoryService.java
  src/services/interfaces/IRoomCategoryService.java
Labels: backend
