Repository Abayev-Bayazit1/Project_5, pull requests merged in 2025-01, with the labels that each got.

#66 Added void start in MyApplication and Main/ also fix some bugs
  src/Main.java
  src/MyApplication.java
  src/controllers/BookingController.java
  src/controllers/HotelController.java
  src/controllers/RoomController.java
  src/models/Room.java
  src/repository/HotelRepository.java
  src/repository/RoomRepository.java
  src/services/BookingService.java
  src/services/HotelService.java
  src/services/RoomService.java
Labels: bug, Classes and Packages, backend, frontend(menu in console)

#68 added admin panel
  src/Main.java
  src/MyApplication.java
  src/controllers/UserController.java
  src/controllers/interfaces/IUserController.java
  src/models/User.java
  src/repository/RoomRepository.java
  src/repository/UserRepository.java
  src/repository/interfaces/IUserRepository.java
  src/services/UserService.java
  src/services/interfaces/IUserService.java
Labels: backend

#70 fix bug
  src/MyApplication.java
  src/controllers/RoomController.java
  src/models/Booking.java
  src/models/Customer.java
  src/models/Hotel.java
  src/models/Room.java
  src/models/User.java
  src/repository/RoomRepository.java
  src/repository/interfaces/IUserRepository.java
  src/services/HotelService.java
  src/services/RoomService.java
  src/services/interfaces/IUserService.java
Labels: bug

#72 RoomCategory
  src/models/RoomCategory.java
Labels: Classes and Packages
